# Site settings
title: QuadForge
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.quadforge.net" # the base hostname & protocol for your site
github_username:  QuadForge

# Build settings
markdown: kramdown
