# Site settings
title: QuadForge
email: quadforge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://jekyll.quadforge.net" # the base hostname & protocol for your site
baseurl:
twitter_username: jekyllrb
github_username:  QuadForge

# Build settings
markdown: kramdown
